language: rust
cache: cargo
rust:
    - stable
    - beta
    - nightly
os:
    - linux
    - osx

before_script:
    - |
      (travis_wait rustup component add rustfmt-preview || true) &&
      (travis_wait rustup component add clippy-preview || true)

script:
    - |
      export PATH="$PATH":~/.cargo/bin &&
      export RUST_BACKTRACE=1 &&
      cargo build &&
      cargo test --release --all &&
      cargo doc --no-deps --all &&
      (test "$TRAVIS_RUST_VERSION" != nightly || cargo test --release --benches --all) &&
      cargo clippy --all -- --deny clippy &&
      cargo fmt --all -- --check

matrix:
    allow_failures:
        - rust: nightly
